### ISSUE TITLE
USER STORY: Top rated movies

### ISSUE THREAD

**Issue by Vasileios20** [Vasileios20/MovieHub#10]
As a **Site User** I can **visit a page** so that **I can view the top rated movies**

 Acceptance Criteria:
- When the user navigates to the "Top Movies" section, the system should display a list of the top 15 movies.
- The movies should be ranked in descending order based on rating average.
- Each movie in the list should display essential information such as title, release year and rating.
- Clicking on a movie should lead to a detailed page with more information about that specific movie.
- The list of top movies and the detailed movie pages should be responsive and accessible on various devices (desktop, tablet, mobile).

# Tasks
- [x] Implement a function to get and display movies by ranking.
- [x] Design html template to display movies in in descending order.
- [x] Ensure that the UI is responsive and functions well on different devices.
