### ISSUE TITLE
USER STORY: Edit comment

### ISSUE THREAD

**Issue by Vasileios20** [Vasileios20/MovieHub#21]
As a **Registered User** I can **edit my comments** so that **manage the content on the platform more effectively**

# Acceptance Criteria:
- I should be able to see a "Delete" option next to my own comments.
- I should not see the "Edit" option next to comments made by other users.
- When a comment is edited, the timestamp of the last edit should be updated.
- Display a confirmation message upon successful comment edit.
- Handle and display appropriate error messages if the comment edit fails.
- Implement proper authentication and authorization checks to ensure only the comment owner can edit their comment.

# Tasks:
- [ ]  Add a "Edit" option next to comments for the user who created them.
- [ ]  Ensure the "Edit" option is not visible for comments made by other users.
- [ ] Implement function to handle comment edits.
- [ ] Implement the logic to update the timestamp when a comment is edited.
- [ ] Display a confirmation message upon successful comment edit.
- [ ] Implement a check for user permissions to ensure that only authorized users can delete comments.
