### ISSUE TITLE
USER STORY: Delete from favourites list

### ISSUE THREAD

**Issue by Vasileios20** [Vasileios20/MovieHub#9]
As a **Registered User** I can **click to remove a movie from my favourites** so that **I can update my favourites list**

# Acceptance Criteria:
- User should be able to remove a movie from their favourites list, and it should no longer appear in the list after removal.
- User should be redirected to favourites list page.

# Tasks
- [x] Implement the logic to delete a movie from the favourites list.
- [x] Ensure after deleting a movie from list rederict to favourites list page.
- [x] Implement message to inform the user that the movie has been added to the favoutirtes list.
